### ISSUE TITLE
About page content

### ISSUE THREAD

**Issue by codebru** [OpenCodeClub/OpenCodeClub.github.io#11]
The about page needs actual content as it currently just has placeholder text. As the host of the meetup, @yamiacat should have the overall say on this but I suggest something along the lines of what @yamiacat says to new people:
- Unstructured coding meetup
- People hang out and code or talk as little or as much as they want
This but in more verbose words.

**Comment by MicahMutsani** [comment]
I'll do this!

**Comment by yamiacat** [comment]
It's a friendly informal meetup for people interested in coding

All ability levels welcome, from beginners to professionals

You can interact as much as you like - if you want to plug in headphones, ignore everyone, and work on your project, that's ok! If you want to talk to everyone that's ok too!

Power and wifi is available

Sometimes the cafe has left over cakes they give us for free!
